{
 "title": "Server Metrics",
 "description": "General metrics for the server.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "at_total_requests", "legendFormat": "Requests" }
   ]
  },
  {
   "title": "Requests Processing Duration (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(at_requests_processing_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "Duration p95"
    }
   ]
  },
  {
   "title": "400 Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "at_400_errors", "legendFormat": "Errors" }
   ]
  },
  {
   "title": "500 Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "at_500_errors", "legendFormat": "Errors" }
   ]
  },
  {
   "title": "POST /transcript",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    { "expr": "at_post_transcript_requests", "legendFormat": "Uploads" }
   ]
  },
  {
   "title": "Rate of POST /transcript",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "rate(at_post_transcript_requests[$__rate_interval])",
     "legendFormat": "Upload Rate"
    }
   ]
  },
  {
   "title": "POST /transcript Duration (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(at_post_transcript_processing_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "Duration p95"
    }
   ]
  },
  {
   "title": "GET /transcript/:id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "targets": [
    { "expr": "at_get_transcript_requests", "legendFormat": "Retrievals" }
   ]
  },
  {
   "title": "Rate of GET /transcript/:id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "rate(at_get_transcript_requests[$__rate_interval])",
     "legendFormat": "Retrieval Rate"
    }
   ]
  },
  {
   "title": "GET /transcript/:id Duration (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(at_get_transcript_processing_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "Duration p95"
    }
   ]
  },
  {
   "title": "GET /transcripts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "targets": [
    { "expr": "at_search_transcripts_requests", "legendFormat": "Queries" }
   ]
  },
  {
   "title": "Rate of GET /transcripts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "targets": [
    {
     "expr": "rate(at_search_transcripts_requests[$__rate_interval])",
     "legendFormat": "Query Rate"
    }
   ]
  },
  {
   "title": "GET /transcripts Duration (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(at_search_transcripts_processing_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "Duration p95"
    }
   ]
  },
  {
   "title": "GET /graph/:id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "targets": [
    { "expr": "at_get_graph_requests", "legendFormat": "Requests" }
   ]
  },
  {
   "title": "Rate of GET /graph/:id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "targets": [
    {
     "expr": "rate(at_get_graph_requests[$__rate_interval])",
     "legendFormat": "Request Rate"
    }
   ]
  },
  {
   "title": "GET /graph/:id Duration (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(at_get_graph_processing_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "Duration p95"
    }
   ]
  },
  {
   "title": "GET /graph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "targets": [
    { "expr": "at_get_all_graph_requests", "legendFormat": "Queries" }
   ]
  },
  {
   "title": "Rate of GET /graph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
   "targets": [
    {
     "expr": "rate(at_get_all_graph_requests[$__rate_interval])",
     "legendFormat": "Query Rate"
    }
   ]
  },
  {
   "title": "GET /graph Duration (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(at_get_all_graph_processing_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "Duration p95"
    }
   ]
  },
  {
   "title": "GET /stream/:id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "at_get_stream_metadata_requests",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Rate of GET /stream/:id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
   "targets": [
    {
     "expr": "rate(at_get_stream_metadata_requests[$__rate_interval])",
     "legendFormat": "Request Rate"
    }
   ]
  },
  {
   "title": "GET /stream/:id Duration (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(at_get_stream_metadata_processing_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "Duration p95"
    }
   ]
  },
  {
   "title": "GET /membership/verify",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
   "targets": [
    { "expr": "at_verify_membership_requests", "legendFormat": "Requests" }
   ]
  },
  {
   "title": "Rate of GET /membership/verify",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 64 },
   "targets": [
    {
     "expr": "rate(at_verify_membership_requests[$__rate_interval])",
     "legendFormat": "Request Rate"
    }
   ]
  },
  {
   "title": "GET /membership/verify Duration (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(at_verify_membership_processing_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "Duration p95"
    }
   ]
  }
 ]
}