{
 "title": "Key Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Streams",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "lt_activated_streams_per_key", "legendFormat": "{{key}}: {{stream_title}}" }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "lt_clients_per_key", "legendFormat": "{{key}}" }
   ]
  },
  {
   "title": "Frame Downloads by Stream",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "lt_stream_frame_downloads_per_key",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Total Frame Downloads",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lt_total_frame_downloads_per_key",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Audio Played by Stream",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 16 },
   "targets": [
    { "expr": "lt_stream_audio_played_per_key", "legendFormat": "{{key}}" }
   ]
  },
  {
   "title": "Total Audio Played",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lt_total_audio_played_per_key", "legendFormat": "{{key}}" }
   ]
  },
  {
   "title": "Video Clipped by Stream",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "lt_stream_video_clipped_per_key",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Total Video Clipped",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lt_total_video_clipped_per_key", "legendFormat": "{{key}}" }
   ]
  },
  {
   "title": "Audio Clipped by Stream",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "lt_stream_audio_clipped_per_key",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Total Audio Played",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lt_total_audio_clipped_per_key", "legendFormat": "{{key}}" }
   ]
  }
 ]
}